// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalentNetworDAL.Models;

#nullable disable

namespace TalentNetworDAL.Migrations
{
    [DbContext(typeof(TalentNetworkContext))]
    partial class TalentNetworkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalentNetworDAL.Models.Faq", b =>
                {
                    b.Property<int>("FaqId")
                        .HasColumnType("int")
                        .HasColumnName("FaqID");

                    b.Property<string>("Answer")
                        .HasMaxLength(68)
                        .HasColumnType("nchar(68)")
                        .IsFixedLength();

                    b.Property<string>("Question")
                        .HasMaxLength(68)
                        .HasColumnType("nchar(68)")
                        .IsFixedLength();

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FaqId");

                    b.HasIndex("UserId");

                    b.ToTable("Faqs");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.ProjectsForTalent", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("ProjectPrice")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectsForTalents");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.TalentUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("ContactPhone")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("TalentUsers");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            IsAdmin = 1,
                            Password = "AQAAAAEAACcQAAAAEF0yg+txDUNebuNSw+ieaIC/H0Xeu+MUqB/doLTDmBR59cwAl+QwMkMftjY2SMh7ww==",
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 11,
                            IsAdmin = 2,
                            Password = "AQAAAAEAACcQAAAAEF0yg+txDUNebuNSw+ieaIC/H0Xeu+MUqB/doLTDmBR59cwAl+QwMkMftjY2SMh7ww==",
                            UserName = "u1"
                        });
                });

            modelBuilder.Entity("TalentNetworDAL.Models.Faq", b =>
                {
                    b.HasOne("TalentNetworDAL.Models.User", "User")
                        .WithMany("Faqs")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Faqs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.ProjectsForTalent", b =>
                {
                    b.HasOne("TalentNetworDAL.Models.User", "User")
                        .WithMany("ProjectsForTalents")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_ProjectsForTalents_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.TalentUser", b =>
                {
                    b.HasOne("TalentNetworDAL.Models.User", "User")
                        .WithOne("TalentUser")
                        .HasForeignKey("TalentNetworDAL.Models.TalentUser", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TalentUsers_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TalentNetworDAL.Models.User", b =>
                {
                    b.Navigation("Faqs");

                    b.Navigation("ProjectsForTalents");

                    b.Navigation("TalentUser");
                });
#pragma warning restore 612, 618
        }
    }
}
